# docker-compose.yml
version: '3'

services:
  postgres:
    image: postgres
    container_name: 'abozar_app_postgres'
    environment:
      #- POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=AWT
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgresData:/var/lib/postgresql/data
    logging:
        driver: none
  redis:
    image: redis
    restart: always
    container_name: 'abozar_app_redis'
    command: redis-server
    ports:
      - '6379:6379'
  api_watch_tower_single:
    build: .
    restart: always
    container_name: 'api_watch_tower_single'
    command: bash -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
#    volumes:
#      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    environment:
      - AAD_TENANT_ID=34a8a6cd-0d53-4aa4-a1d5-5dd854433b2d
      - AAD_CLIENT_ID=e5e24664-df2b-4492-8ff0-edcf3c72d53e
  celery:
    build: .
    container_name: 'abozar_app_celery'
    command: celery -A ApiWatchTower worker -B --concurrency=10
#    volumes:
#      - .:/code
    links:
      - redis
    depends_on:
      - api_watch_tower_single
      - redis
      - postgres
    environment:
      - AAD_TENANT_ID=34a8a6cd-0d53-4aa4-a1d5-5dd854433b2d
      - AAD_CLIENT_ID=e5e24664-df2b-4492-8ff0-edcf3c72d53e
  celery-beat:
    build: .
    restart: always
    container_name: 'abozar_app_celery_beat'
    command: celery -A ApiWatchTower beat -l info -S django --pidfile=
#    volumes:
#      - .:/code
    links:
      - redis
    depends_on:
      - api_watch_tower_single
      - redis
      - celery
      - postgres
    environment:
      - AAD_TENANT_ID=34a8a6cd-0d53-4aa4-a1d5-5dd854433b2d
      - AAD_CLIENT_ID=e5e24664-df2b-4492-8ff0-edcf3c72d53e
  grafana:
    image: grafana/grafana:latest
    container_name: 'abozar_app_grafana'
    ports:
      - 3000:3000
    volumes:
      - ./grafana-storage:/var/lib/grafana
#      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - postgres
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=abozar

volumes:
    postgresData: